Forum Topic/Forum Topic/Models/Topic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Forum_Topic.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public class Topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topic()
        {
            this.reply = new HashSet<Reply>();
            this.tag_topic = new HashSet<TagTopic>();
        }

        public int id { get; set; }
        public string title { get; set; }
        [AllowHtml]
        public string description { get; set; }
        public System.DateTime creation_date { get; set; }

        public string url_file { get; set; }
        public int id_user { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reply> reply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagTopic> tag_topic { get; set; }
        public virtual User user_forum { get; set; }

        /// <summary>
        /// Method that create the current date time
        /// </summary>
        /// <param name="topic"></param>
        public void setCreateDate (Topic topic)
        {
            topic.creation_date = DateTime.Now;
        }

        /// <summary>
        /// Method that create url
        /// </summary>
        /// <param name="topic"></param>
        /// <param name="file_name"></param>
        public void setUrlFile(Topic topic, string file_name)
        {
            topic.url_file = file_name;
        }

    }
}

Forum Topic/Forum Topic/Controllers/ReplyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Forum_Topic;
using Forum_Topic.Models;
using Forum_Topic.Utils;

namespace Forum_Topic.Controllers
{
    public class ReplyController : Controller
    {
        private Forum_TopicEntities db = new Forum_TopicEntities();

        /// <summary>
        /// Method create a new replay
        /// </summary>
        /// <param name="reply">reply to save</param>
        /// <param name="id_topic">idtopic assigned to that reply</param>
        /// <returns>Redirect to details of topic</returns>
        public ActionResult CreateReply(Reply reply, int id_topic, HttpPostedFileBase url_file)
        {
            /*Asing Topic to reply*/
            reply.addUserToReply(reply, id_topic);

            reply.setCreateDate(reply);

            if (url_file != null)
            {
                FileManipulation.saveFile(url_file, Server.MapPath("~/gallery"));
                reply.setUrlFile(reply, url_file.FileName);
            }

            /*Add user to reply*/
            if (Session["User_Id"] != null)
                reply.id_user = Int32.Parse(Session["User_Id"].ToString());
            else
                reply.id_user = 1; // If we forget to login all topic is created for administrator

            /*Increments max_reply*/
            User user = db.Users.Find(reply.id_user);
            user.incrementMaxReply(user);

            if (ModelState.IsValid)
            {
                db.Replies.Add(reply);
                db.SaveChanges();
                //return RedirectToAction("Details", "Topic", id_topic);
                return RedirectToAction("Details", new RouteValueDictionary(
                    new { controller = "Topic", action = "Details", Id = id_topic }));
            }

            return View();
        }

        // GET: Reply/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reply reply = db.reply.Find(id);
            if (reply == null)
            {
                return HttpNotFound();
            }
            return View(reply);
        }

        // POST: Reply/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reply reply = db.reply.Find(id);
            reply.user_forum.decrementMaxReply(reply.user_forum);
            db.reply.Remove(reply);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Forum Topic/Forum Topic/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Forum_Topic;
using Forum_Topic.Models;
using Forum_Topic.Utils;

namespace Forum_Topic.Controllers
{
    public class TopicController : Controller
    {
        private Forum_TopicEntities db = new Forum_TopicEntities();

        /// <summary>
        /// Index view after login, we show the most recently Topics created in the system
        /// </summary>
        /// <returns>Index view with all recently topics</returns>
        public ActionResult Index()
        {
            List<Topic> AllTopicsListOrdered = new List<Topic>();

            using (var context = db)
            {
                AllTopicsListOrdered = context.Topics
                            .OrderByDescending(x => x.creation_date)
                            .Include(y => y.user_forum)
                            .ToList<Topic>();
            }

            return View(AllTopicsListOrdered);
        }

        /// <summary>
        /// Show top 10 topic by user in the system
        /// </summary>
        /// <returns></returns>
        public ActionResult TopTopicUser()
        {
            List<User> AllTopicsListOrdered = new List<User>();

            try
            {
                using (var context = db)
                {
                    AllTopicsListOrdered = context.Users
                               .OrderByDescending(x => x.max_topic)
                               .Take(10)
                               .ToList<User>();
                }
            } catch (Exception ex)
            {

            }


            return View("MostTopicUser", AllTopicsListOrdered);
        }

        /// <summary>
        /// Search method to find the title of whatever topic.
        /// </summary>
        /// <param name="search_name"></param>
        /// <returns>Index with the topic filtered</returns>
        public ActionResult Search(string search_name)
        {
            List<Topic> AllTopicsListOrdered = new List<Topic>();

            try
            {
                using (var context = db)
                {
                    AllTopicsListOrdered = context.Topics
                              .OrderByDescending(x => x.title)
                              .Where(b => b.title.Trim().ToLower().Contains(search_name.Trim().ToLower()))
                              .Include(y => y.user_forum)
                              .ToList<Topic>();
                }
            } catch (Exception ex)
            {

            }

            return View("Index", AllTopicsListOrdered);
        }


        /// <summary>
        /// Detail view for topics also you can reply in this view for a specific topic
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            BigModel model = new BigModel();
            model.topic = topic;

            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        /// <summary>
        /// Method who call the view for create a new topic
        /// </summary>
        /// <returns>create view</returns>
        public ActionResult CreateForm()
        {
            return View("Create");
        }

        // POST: Topic/Create
        /// <summary>
        /// Method that create a new topic, it is assssigned to a user logged but if the user is not, then by default is the user 1
        /// </summary>
        /// <param name="topic">The topic we want to save</param>
        /// <returns>view index topic</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title,description")] Topic topic, HttpPostedFileBase url_file)
        {
            topic.setCreateDate(topic);

            if (url_file != null)
            {
                FileManipulation.saveFile(url_file, Server.MapPath("~/gallery"));
                topic.setUrlFile(topic, url_file.FileName);
            }
            
            if (Session["User_Id"] != null)
                topic.id_user = Int32.Parse(Session["User_Id"].ToString());
            else
                topic.id_user = Int32.Parse(Session["User_Id"].ToString()); // If we forget to login all topic is created for administrator

            User user = new User();

            try
            {
                user = db.Users.Find(topic.id_user);
                user.incrementMaxTopic(user); //Increments max topic of user, reference objects is passed so it's going to be modify
            } catch (Exception ex)
            {

            }

            if (ModelState.IsValid)
            {
                db.Topics.Add(topic);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(topic);
        }

        /// <summary>
        /// Method that dowload the file linked to a topic
        /// </summary>
        /// <param name="file_name"></param>
        /// <returns> File to dowload</returns>
        public FileResult DowloadFile(string file_name) {
            string path_file = Path.Combine(Server.MapPath("~/gallery"),
                                               Path.GetFileName(file_name));

            byte[] fileBytes = System.IO.File.ReadAllBytes(@path_file);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, file_name);
        }

        // GET: Topic/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // POST: Topic/Edit/5
        /// <summary>
        /// Method used to edit a topic
        /// </summary>
        /// <param name="topic">Topic we want to edit</param>
        /// <returns>view index topic</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,description")] Topic topic)
        {
            topic.creation_date = DateTime.Now;

            if (Session["User_Id"] != null)
                topic.id_user = Int32.Parse(Session["User_Id"].ToString());
            else
                topic.id_user = 1; // If we forget to login all topic is created for administrator

            if (ModelState.IsValid)
            {
                db.Entry(topic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(topic);
        }

        // GET: Topic/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        /// <summary>
        /// Delete the topic with all reply assigned to it
        /// </summary>
        /// <param name="id"></param>
        /// <returns>view index topic</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Topic topic = db.Topics.Find(id);
            topic.user_forum.decrementMaxTopic(topic.user_forum); //Derenent max topic when is deleted

            //Delete all foreing key from reply
            foreach (Reply reply in topic.reply.ToList())
            {
                db.Replies.Remove(reply);
            }

            db.Topics.Remove(topic);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Forum Topic/Forum Topic/Views/Topic/Create.cshtml
@model Forum_Topic.Models.Topic

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Topic", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Topic</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.TextArea("description", new { @class = "form-control", @id = "Eso" })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.url_file, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="url_file" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to topic", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/tinymce/tiny_mce.js"></script>
    <script src="~/Scripts/Main.js"></script>
}

Forum Topic/Forum Topic/Views/Topic/Delete.cshtml
@model Forum_Topic.Models.Topic

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Topic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.creation_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.creation_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_user)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_user)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Forum Topic/Forum Topic/Views/Topic/Details.cshtml
@model Forum_Topic.Models.BigModel

@{
    ViewBag.Title = "Details";
}

<h2>Detail topic</h2>

<div>
    <h4>Topic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.topic.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.topic.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.topic.description)
        </dt>

        <dd>
            @Html.Raw(Model.topic.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.topic.creation_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.topic.creation_date)
        </dd>

        <dt>
            @Html.Label("User Creator")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.topic.user_forum.name)
        </dd>
    </dl>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <h4>Replies: </h4>

                @foreach (var item in Model.topic.reply)
                {

                    @Html.Label("Written by: ")
                    @Html.DisplayFor(modelItem => item.user_forum.name)
                    <br>
                    @Html.Label("Reply text: ")
                    @Html.DisplayFor(modelItem => item.description)
                    <br>
                    if (item.url_file != null)
                    {
                        @Html.ActionLink("Dowload File", "DowloadFile", new { file_name = item.url_file })
                    }
                    <br><br>
                }

                @using (Html.BeginForm("CreateReply", "Reply", new { id_topic = Model.topic.id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Label("Write your reply")
                        <div class="col-md-10">
                            @Html.EditorFor(o => o.reply.description)
                            @Html.ValidationMessageFor(model => model.reply.description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.reply.url_file, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="url_file" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.topic.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Forum Topic/Forum Topic/Views/Topic/Edit.cshtml
@model Forum_Topic.Models.Topic

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Topic</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Forum Topic/Forum Topic/Views/Topic/Index.cshtml
@model IEnumerable<Forum_Topic.Models.Topic>

@{
    ViewBag.Title = "Index";
}

<h2>Recent Topics Ordered</h2>

@using (Html.BeginForm("TopTopicUser", "Topic", FormMethod.Get))
{
    <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Most Topic users</button>
}


<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    @Html.ActionLink("Create", "CreateForm")
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            @using (Html.BeginForm("Search", "Topic"))
            {
                <div class="input-group">
                    <input id="search" type="text" name="search_name" class="form-control" placeholder="Search Here..." />
                    <span class="input-group-btn">
                        <button class="btn btn-lg btn-primary center-block" type="submit">Search</button>
                    </span>
                </div>
            }
        </div>
    </div>
</div>

<br>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.creation_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.user_forum.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.url_file)
        </th>
        <th></th>
    </tr>

    @foreach (var topic in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => topic.title)
            </td>
            <td>
                @Html.Raw(topic.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => topic.creation_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => topic.user_forum.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => topic.url_file)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = topic.id }) |
                @Html.ActionLink("Edit", "Edit", new { id = topic.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = topic.id }) |
                @if (topic.url_file != null)
                {
                    @Html.ActionLink("Dowload File", "DowloadFile", new { file_name = topic.url_file })
                }
            </td>
        </tr>
    }

</table>

Forum Topic/Forum Topic/Views/Topic/MostTopicUser.cshtml
@model IEnumerable<Forum_Topic.Models.User>

@{
    ViewBag.Title = "Most Topic Users Top 10";
}

<h2>Most Topic Users</h2>

@foreach (var item in Model)
{
<div>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.Label("User Name:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => item.name)
                        </dd>

                        <dt>
                            @Html.Label("Max Number Of Topics Created: ")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => item.max_topic)
                        </dd>

                        <dt>
                            @Html.Label("Max Number Of Replies Created: ")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => item.max_reply)
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
 </div>
                }
<p>
    @Html.ActionLink("Back to List", "Index")
</p>